// All product data for SN Fabrics
export interface Product {
  id: number;
  slug: string;
  name: string;
  websiteName: string;
  description: string;
  qualityDescription: string;
  weight?: string;
  priceRange: string;
  width: string;
  usedFor: string;
  whatsappMsg: string;
  category: 'velvet' | 'specialty';
  featured?: boolean;
}

export const PRODUCTS: Product[] = [
  {
    id: 1,
    slug: 'makhan-velvet',
    name: 'Makhan Velvet',
    websiteName: 'Makhan Single Tone',
    description: 'Makhan Velvet is loved for its ultra-soft, buttery feel and smooth, rich texture. It has a graceful fall and a subtle shine that gives every outfit a premium look without feeling heavy. It combines comfort with elegance effortlessly.',
    qualityDescription: 'Perfect for sarees, lehengas, blouses, gowns, and garments',
    weight: '19 kg',
    priceRange: '₹200/mtr',
    width: "44'",
    usedFor: 'Sarees, Lehengas, Blouses, Gowns',
    whatsappMsg: "Hello SN Fabrics! I'm interested in *Makhan Velvet (Single Tone, 44')* — ultra-soft, buttery feel. Could you please share availability, colours and pricing? Thank you!",
    category: 'velvet',
    featured: true,
  },
  {
    id: 2,
    slug: 'micro-velvet-9000',
    name: 'Micro Velvet 9000',
    websiteName: 'Micro Velvet 9000 Single Tone',
    description: 'Micro Velvet 9000 is a lightweight, 100% polyester velvet with a soft touch and elegant shine. It is thin, easy to handle, and drapes well, making it a practical yet stylish choice.',
    qualityDescription: 'Lightweight polyester velvet with elegant drape',
    weight: '18.5 kg',
    priceRange: '₹101/mtr',
    width: "44' / 54'",
    usedFor: 'Ethnic Wear, Drapes, Curtains',
    whatsappMsg: "Hello SN Fabrics! I'm interested in *Micro Velvet 9000 (Single Tone)* — lightweight 100% polyester velvet. Could you please share available shades, width (44'/54') and current pricing? Thank you!",
    category: 'velvet',
    featured: true,
  },
  {
    id: 3,
    slug: 'micro-velvet-9000-crush',
    name: 'Velvet 9000 Crush',
    websiteName: 'Micro Velvet 9000 Crush',
    description: "A perfect blend of richness and texture, Velvet 9000 Crush is known for its distinctive crushed finish that adds depth and dimension to every design. With a soft touch and subtle sheen, this fabric creates a statement look.",
    qualityDescription: 'Crushed finish velvet with depth and dimension',
    priceRange: '₹100–105/mtr',
    width: "44'",
    usedFor: 'Occasion Wear, Drapes, High-End Garments',
    whatsappMsg: "Hello SN Fabrics! I'm interested in *Micro Velvet 9000 Crush (44')* — crushed finish velvet with rich texture. Could you please share available colours and pricing? Thank you!",
    category: 'velvet',
  },
  {
    id: 4,
    slug: 'micro-velvet-11000',
    name: 'Micro Velvet 11000',
    websiteName: 'Micro Velvet 11000 Single Tone',
    description: 'Micro Velvet 11000 offers a richer and slightly thicker feel for a more premium look. With deeper colours, a smoother finish, and a beautiful fall, it stands out in occasion and bridal wear.',
    qualityDescription: 'Richer, thicker velvet for premium occasion wear',
    weight: '22 kg',
    priceRange: '₹80–85/mtr',
    width: "44'",
    usedFor: 'Lehengas, Sherwanis, Bridal Wear',
    whatsappMsg: "Hello SN Fabrics! I'm interested in *Micro Velvet 11000 (Single Tone, 44')* — richer, thicker premium velvet. Could you please share colour options and current pricing? Thank you!",
    category: 'velvet',
    featured: true,
  },
  {
    id: 5,
    slug: 'ice-velvet',
    name: 'Ice Velvet',
    websiteName: 'Ice Velvet',
    description: 'Ice Velvet offers a smooth, cool-toned finish with a gentle shine that reflects understated sophistication. Lightweight yet plush, it provides a sleek and modern appeal, perfect for contemporary designs.',
    qualityDescription: 'Cool-toned velvet with smooth sleek finish',
    weight: '21 kg',
    priceRange: '₹100–105/mtr',
    width: "44'",
    usedFor: 'Contemporary Fashion, Fluid Silhouettes',
    whatsappMsg: "Hello SN Fabrics! I'm interested in *Ice Velvet (44')* — smooth cool-toned finish with gentle shine. Could you please share available shades and pricing? Thank you!",
    category: 'velvet',
  },
  {
    id: 6,
    slug: 'velvet-99999',
    name: 'Velvet 99999',
    websiteName: 'Velvet 99999 — Single Tone',
    description: 'Crafted for those who demand the finest, Velvet 99999 represents superior quality with an ultra-soft hand feel and a rich, dense texture. Its luxurious finish and durability make it ideal for high-end creations.',
    qualityDescription: 'Ultra-soft, dense, durable premium velvet',
    weight: '26 kg',
    priceRange: '₹180–185/mtr',
    width: "44'",
    usedFor: 'High-End Couture, Designer Garments',
    whatsappMsg: "Hello SN Fabrics! I'm interested in *Velvet 99999 (Single Tone, 44')* — ultra-premium dense velvet. Could you please share colours and bulk pricing? Thank you!",
    category: 'velvet',
  },
  {
    id: 7,
    slug: 'velvet-99999-crush',
    name: 'Velvet 99999 Crush',
    websiteName: 'Velvet 99999 Crush — Single Tone',
    description: 'An elevated version of our premium range, Velvet 99999 Crush combines the richness of top-grade velvet with a textured crushed effect. The interplay of light and shadow creates a bold, glamorous look.',
    qualityDescription: 'Premium velvet + crushed texture — bold and glamorous',
    priceRange: '₹250–255/mtr',
    width: "44'",
    usedFor: 'Statement Outfits, Designer Collections',
    whatsappMsg: "Hello SN Fabrics! I'm interested in *Velvet 99999 Crush (Single Tone, 44')* — premium crushed velvet. Could you please share colour availability, min. order quantity and pricing? Thank you!",
    category: 'velvet',
  },
  {
    id: 8,
    slug: 'velvet-embroidery',
    name: 'Velvet Embroidery',
    websiteName: 'Velvet Embroidery Work',
    description: 'Our Velvet Embroidery Work fabric showcases intricate craftsmanship on a rich velvet base, blending texture with detailed artistry. Ideal for festive and couture wear, it brings elegance and design precision together.',
    qualityDescription: 'Intricate embroidery on premium velvet base',
    priceRange: 'As per design',
    width: "44'",
    usedFor: 'Festive Wear, Couture, Bridal',
    whatsappMsg: "Hello SN Fabrics! I'm interested in *Velvet Embroidery Work (44')* — intricate craftsmanship on velvet. Could you please share design catalogue and pricing? Thank you!",
    category: 'velvet',
  },
  {
    id: 9,
    slug: 'fendy',
    name: 'Fendy (NC Satin)',
    websiteName: 'Fendy — NC Satin',
    description: 'Inspired by the iconic aesthetic of Fendi, this fabric features bold patterns, signature motifs, and a premium finish. Designed for modern, fashion-forward creations combining global luxury with versatile usability.',
    qualityDescription: 'Bold patterns, premium satin finish, fashion-forward',
    weight: '9 kg',
    priceRange: '₹42–44/mtr',
    width: "44'",
    usedFor: 'Modern Garments, Statement Pieces',
    whatsappMsg: "Hello SN Fabrics! I'm interested in *Fendy / NC Satin (44')* — bold patterns and premium finish. Could you please share available motifs and pricing? Thank you!",
    category: 'specialty',
  },
  {
    id: 10,
    slug: 'sindoor',
    name: 'Sindoor Fabric',
    websiteName: 'Sindoor',
    description: 'Sindoor Fabric is a vibrant and striking textile known for its rich, deep red tone that symbolizes tradition, celebration, and timeless elegance. With a smooth finish and graceful fall, it is widely preferred for ethnic wear.',
    qualityDescription: 'Vibrant deep red tone — smooth finish, graceful fall',
    weight: '9 kg',
    priceRange: '₹40–42/mtr',
    width: "44'",
    usedFor: 'Ethnic Wear, Festive Collections, Statement Pieces',
    whatsappMsg: "Hello SN Fabrics! I'm interested in *Sindoor Fabric (44')* — rich deep red with smooth finish. Could you please share availability, variants and pricing? Thank you!",
    category: 'specialty',
  },
];
